-- MySQL Script generated by MySQL Workbench

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_galu
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_galu` DEFAULT CHARACTER SET utf8 ;
USE `db_galu` ;

-- -----------------------------------------------------
-- Table `db_galu`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_galu`.`rol` (
  `id_rol` VARCHAR(50) NOT NULL,
  `rol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `db_galu`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_galu`.`usuarios` (
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `avatar` VARCHAR(200) NOT NULL,
  `id_rol` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`correo`),
    FOREIGN KEY (`id_rol`)
    REFERENCES `db_galu`.`rol` (`id_rol`)
    )
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
